Fix a small error, add more logging
response.getEntity() causes

FATAL: Attempted read from closed stream.
java.io.IOException: Attempted read from closed stream.

Since NetUtils.upload already does response.getEntity()